"""full schema (existing + platform tables)

Revision ID: 24e4ba8f4fd2
Revises: 067fde50f4bf
Create Date: 2026-08-19 13:13:02.150097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '24e4ba8f4fd2'
down_revision: Union[str, None] = '067fde50f4bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('correlation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('handled', sa.Boolean(), nullable=False),
    sa.Column('handled_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('handled_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_correlation_id'), 'event', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_event_event_type'), 'event', ['event_type'], unique=False)
    op.create_index(op.f('ix_event_published_at'), 'event', ['published_at'], unique=False)
    op.create_table('mailmessage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sender_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('department', sa.Enum('PROCUREMENT', 'MAINTENANCE', 'FINANCE', 'HSE', 'PRODUCTION', 'MATERIAL_MANAGEMENT', 'WAREHOUSE_MANAGEMENT', 'SALES_DISTRIBUTION', 'SUPPLY_CHAIN_MANAGEMENT', 'ADMIN', name='department'), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('has_attachment', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('department', sa.Enum('PROCUREMENT', 'MAINTENANCE', 'FINANCE', 'HSE', 'PRODUCTION', 'MATERIAL_MANAGEMENT', 'WAREHOUSE_MANAGEMENT', 'SALES_DISTRIBUTION', 'SUPPLY_CHAIN_MANAGEMENT', 'ADMIN', name='department'), nullable=False),
    sa.Column('level', sa.Enum('MANAGER', 'SENIOR_MANAGER', 'DEPT_HEAD', 'ADMIN', name='level'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('workflow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('department', sa.Enum('PROCUREMENT', 'MAINTENANCE', 'FINANCE', 'HSE', 'PRODUCTION', 'MATERIAL_MANAGEMENT', 'WAREHOUSE_MANAGEMENT', 'SALES_DISTRIBUTION', 'SUPPLY_CHAIN_MANAGEMENT', 'ADMIN', name='department'), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sap_systems', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('non_sap_systems', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('steps_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('exception_reasons_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_key'), 'workflow', ['key'], unique=True)
    op.create_table('auditlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('detail', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditlog_action'), 'auditlog', ['action'], unique=False)
    op.create_index(op.f('ix_auditlog_actor_user_id'), 'auditlog', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_auditlog_created_at'), 'auditlog', ['created_at'], unique=False)
    op.create_table('mailattachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mail_message_id', sa.Integer(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['mail_message_id'], ['mailmessage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mailattachment_mail_message_id'), 'mailattachment', ['mail_message_id'], unique=False)
    op.create_table('workflowaccess',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('granted_by_id', sa.Integer(), nullable=True),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['granted_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflowaccess_user_id'), 'workflowaccess', ['user_id'], unique=False)
    op.create_index(op.f('ix_workflowaccess_workflow_id'), 'workflowaccess', ['workflow_id'], unique=False)
    op.create_table('workflowrun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('triggered_by_id', sa.Integer(), nullable=False),
    sa.Column('department', sa.Enum('PROCUREMENT', 'MAINTENANCE', 'FINANCE', 'HSE', 'PRODUCTION', 'MATERIAL_MANAGEMENT', 'WAREHOUSE_MANAGEMENT', 'SALES_DISTRIBUTION', 'SUPPLY_CHAIN_MANAGEMENT', 'ADMIN', name='department'), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'EXCEPTION', name='runstatus'), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('log_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('result_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['triggered_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflowrun_triggered_by_id'), 'workflowrun', ['triggered_by_id'], unique=False)
    op.create_index(op.f('ix_workflowrun_workflow_id'), 'workflowrun', ['workflow_id'], unique=False)
    op.create_table('aidecision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_run_id', sa.Integer(), nullable=True),
    sa.Column('use_case', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('correlation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('classification', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('recommendation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rules_result', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('final_decision', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('human_decision', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflowrun.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aidecision_correlation_id'), 'aidecision', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_aidecision_created_at'), 'aidecision', ['created_at'], unique=False)
    op.create_index(op.f('ix_aidecision_use_case'), 'aidecision', ['use_case'], unique=False)
    op.create_index(op.f('ix_aidecision_workflow_run_id'), 'aidecision', ['workflow_run_id'], unique=False)
    op.create_table('exceptionitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('department', sa.Enum('PROCUREMENT', 'MAINTENANCE', 'FINANCE', 'HSE', 'PRODUCTION', 'MATERIAL_MANAGEMENT', 'WAREHOUSE_MANAGEMENT', 'SALES_DISTRIBUTION', 'SUPPLY_CHAIN_MANAGEMENT', 'ADMIN', name='department'), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVED', name='exceptionstatus'), nullable=False),
    sa.Column('raised_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by_id', sa.Integer(), nullable=True),
    sa.Column('resolution_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['workflowrun.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exceptionitem_run_id'), 'exceptionitem', ['run_id'], unique=False)
    op.create_index(op.f('ix_exceptionitem_workflow_id'), 'exceptionitem', ['workflow_id'], unique=False)
    op.create_table('integrationlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('system', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('endpoint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('correlation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('workflow_run_id', sa.Integer(), nullable=True),
    sa.Column('request_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('response_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflowrun.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integrationlog_correlation_id'), 'integrationlog', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_integrationlog_created_at'), 'integrationlog', ['created_at'], unique=False)
    op.create_index(op.f('ix_integrationlog_provider'), 'integrationlog', ['provider'], unique=False)
    op.create_index(op.f('ix_integrationlog_system'), 'integrationlog', ['system'], unique=False)
    op.create_index(op.f('ix_integrationlog_workflow_run_id'), 'integrationlog', ['workflow_run_id'], unique=False)
    op.create_table('invoiceextraction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mail_attachment_id', sa.Integer(), nullable=False),
    sa.Column('is_invoice', sa.Boolean(), nullable=False),
    sa.Column('classifier_confidence', sa.Float(), nullable=False),
    sa.Column('classifier_reasons', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vendor_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('invoice_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('invoice_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('po_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('total_amount', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw_ocr_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mail_attachment_id'], ['mailattachment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoiceextraction_mail_attachment_id'), 'invoiceextraction', ['mail_attachment_id'], unique=True)
    op.create_table('workflowstep',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('detail_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['workflowrun.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflowstep_run_id'), 'workflowstep', ['run_id'], unique=False)
    op.create_table('exceptionaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exception_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['exception_id'], ['exceptionitem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exceptionaction_created_at'), 'exceptionaction', ['created_at'], unique=False)
    op.create_index(op.f('ix_exceptionaction_exception_id'), 'exceptionaction', ['exception_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exceptionaction_exception_id'), table_name='exceptionaction')
    op.drop_index(op.f('ix_exceptionaction_created_at'), table_name='exceptionaction')
    op.drop_table('exceptionaction')
    op.drop_index(op.f('ix_workflowstep_run_id'), table_name='workflowstep')
    op.drop_table('workflowstep')
    op.drop_index(op.f('ix_invoiceextraction_mail_attachment_id'), table_name='invoiceextraction')
    op.drop_table('invoiceextraction')
    op.drop_index(op.f('ix_integrationlog_workflow_run_id'), table_name='integrationlog')
    op.drop_index(op.f('ix_integrationlog_system'), table_name='integrationlog')
    op.drop_index(op.f('ix_integrationlog_provider'), table_name='integrationlog')
    op.drop_index(op.f('ix_integrationlog_created_at'), table_name='integrationlog')
    op.drop_index(op.f('ix_integrationlog_correlation_id'), table_name='integrationlog')
    op.drop_table('integrationlog')
    op.drop_index(op.f('ix_exceptionitem_workflow_id'), table_name='exceptionitem')
    op.drop_index(op.f('ix_exceptionitem_run_id'), table_name='exceptionitem')
    op.drop_table('exceptionitem')
    op.drop_index(op.f('ix_aidecision_workflow_run_id'), table_name='aidecision')
    op.drop_index(op.f('ix_aidecision_use_case'), table_name='aidecision')
    op.drop_index(op.f('ix_aidecision_created_at'), table_name='aidecision')
    op.drop_index(op.f('ix_aidecision_correlation_id'), table_name='aidecision')
    op.drop_table('aidecision')
    op.drop_index(op.f('ix_workflowrun_workflow_id'), table_name='workflowrun')
    op.drop_index(op.f('ix_workflowrun_triggered_by_id'), table_name='workflowrun')
    op.drop_table('workflowrun')
    op.drop_index(op.f('ix_workflowaccess_workflow_id'), table_name='workflowaccess')
    op.drop_index(op.f('ix_workflowaccess_user_id'), table_name='workflowaccess')
    op.drop_table('workflowaccess')
    op.drop_index(op.f('ix_mailattachment_mail_message_id'), table_name='mailattachment')
    op.drop_table('mailattachment')
    op.drop_index(op.f('ix_auditlog_created_at'), table_name='auditlog')
    op.drop_index(op.f('ix_auditlog_actor_user_id'), table_name='auditlog')
    op.drop_index(op.f('ix_auditlog_action'), table_name='auditlog')
    op.drop_table('auditlog')
    op.drop_index(op.f('ix_workflow_key'), table_name='workflow')
    op.drop_table('workflow')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_table('mailmessage')
    op.drop_index(op.f('ix_event_published_at'), table_name='event')
    op.drop_index(op.f('ix_event_event_type'), table_name='event')
    op.drop_index(op.f('ix_event_correlation_id'), table_name='event')
    op.drop_table('event')
    # ### end Alembic commands ###
